config/routes.rb
Rails.application.routes.draw do
  root "exchanges#new"

  resources "exchanges", only: [:index, :new, :create]
  post "exchanges/simulate" => "exchanges#simulate"

  resources "pokemons", only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  has_many :exchanged_pokemons, dependent: :destroy

  validate :at_least_one_pokemon_on_each_side?

  scope :history, -> { order(created_at: :desc) }

  def add_pokemon(pokemon, side)
    exchanged_pokemons << ExchangedPokemon.new(pokemon: pokemon, side: side)
  end

  def left_side_pokemons
    exchanged_pokemons.select(&:left?)
  end

  def right_side_pokemons
    exchanged_pokemons.select(&:right?)
  end

  private

  def at_least_one_pokemon_on_each_side?
    return unless left_side_pokemons.empty? || right_side_pokemons.empty?

    errors.add(:exchanged_pokemons, "needs at least one pokemon on each side")
  end
end

app/models/exchanged_pokemon.rb
class ExchangedPokemon < ApplicationRecord
  belongs_to :pokemon
  belongs_to :exchange

  validates :side, presence: true

  enum side: {
    left: 0,
    right: 1
  }

  def score
    pokemon.base_experience
  end

  def name
    pokemon.name
  end
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  validates :name, presence: true
  validates :poke_index, presence: true, uniqueness: true

  scope :search, ->(query) { where("name LIKE ?", "#{sanitize_sql_like(query)}%") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  def new; end

  def index
    @exchanges = ExchangeHistory.call
  end

  def create
    exchange = SimulateExchange.call(exchange_params)
    SaveExchange.call(exchange: exchange)
    head :ok
  end

  def simulate
    exchange = SimulateExchange.call(exchange_params)
    render json: { fair: CheckFairness.call(exchange: exchange) }
  end

  private

  def exchange_params
    params.permit(left: [], right: [])
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    pokemons = GetPokemons.call(search: pokemon_search_params)
    render json: pokemons
  end

  def new; end

  def create
    pokemon = FetchPokemon.call(name: pokemon_params[:name])
    SavePokemon.call(pokemon: pokemon)
    redirect_to new_pokemon_path, notice: "Pokemon created successfully"
  rescue FetchPokemon::PokemonNotFound, SavePokemon::AlreadyExistError => exception
    redirect_to new_pokemon_path, flash: { error: exception.message }
  end

  private

  def pokemon_params
    params.permit(:name)
  end

  def pokemon_search_params
    params[:query]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchange_helper.rb
module ExchangeHelper
  def fairness_footer(exchange)
    if CheckFairness.call(exchange: exchange)
      fair_card_footer
    else
      unfair_card_footer
    end
  end

  def fair_card_footer
    %(
      <div class="card-footer text-primary bg-light">
        <b>Fair trade</b>
      </div>
    ).html_safe
  end

  def unfair_card_footer
    %(
      <div class="card-footer text-warning bg-light">
        <b>Unfair trade</b>
      </div>
    ).html_safe
  end
end

app/views/application/_alert.html.erb
<% if alert %>
  <div class="alert alert-warning" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/application/_error.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger" role="error">
    <%= flash[:error] %>
  </div>
<% end %>

app/views/application/_notice.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

app/views/exchanges/index.html.erb
<div class="container">
  <h1 class="display-2 mb-2">History</h1>

  <% @exchanges.each do |exchange| %>
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="card-title">Trade #<%= exchange.id %></h5>
        <h6 class="card-subtitle mb-4 text-muted"><%= time_ago_in_words(exchange.created_at) %></h6>
        <div class="container-fluid">
          <div class="row">
            <div class="col">
              <% exchange.left_side_pokemons.each do |exchange_pokemon| %>
                <p><strong><%= exchange_pokemon.name %></strong></p>
                <p><small>Base Experience: <%= exchange_pokemon.score %></small></p>
              <% end %>
            </div>
            <div class="col">
              <% exchange.right_side_pokemons.each do |exchange_pokemon| %>
                <p><strong><%= exchange_pokemon.name %></strong></p>
                <p><small>Base Experience: <%= exchange_pokemon.score %></small></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <%= fairness_footer(exchange) %>
    </div>
  <% end %>
</div>

app/views/exchanges/new.html.erb
<div id="poke-trader-app">
</div>

<%= javascript_pack_tag 'poke-trader-app' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poketrader</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
      crossorigin="anonymous"
    >
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
      crossorigin="anonymous"
    >
    </script>
    <link
      rel="stylesheet"
      href="https://unpkg.com/react-bootstrap-typeahead/css/Typeahead.css"
    >

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
      <div class="container">
        <h1 class="navbar-brand">PokeTrader</h1>
        <div class="navbar-nav">
          <%= link_to "New trade", new_exchange_path, class: "nav-link" %>
          <%= link_to "Pokemons", new_pokemon_path, class: "nav-link" %>
          <%= link_to "History", exchanges_path, class: "nav-link" %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <%= render "notice" %>
      <%= render "alert" %>
      <%= render "error" %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/pokemons/new.html.erb
<div class="container">
  <h1 class="display-2 mb-2">Pokemons</h1>

  <div class="card mb-4">
    <div class="card-body bg-light">
      <p class="card-text">If you know a pokemon and it is missing from the trade list, you can add it here!</p>
      <p class="card-text">Just type the pokemon's name and submit.</p>
    </div>
  </div>

  <%= form_tag pokemons_path do %>
    <%= label_tag 'name', nil, class: "form-label" %>
    <%= text_field_tag 'name', nil, class: "form-control mb-4" %>

    <input type="submit" class="btn btn-primary">
  <% end %>
</div>